### ISSUE TITLE
Support for referencing other keys in translation definitions

### ISSUE THREAD

**Issue by Majkl578** [Kdyby/Translation#23]
Assume we have following translation definition file:

``` yml
homepage:
    foo: "Hello World"
    bar: "Hello Friend"
    baz: "Hello World"
```

The reasons may be as simple as different translations in different languages, but in some language, few translations would be same (e.g. czech vs. english).

It would be nice to avoid duplication of these messages, so something like this would do so:

``` yml
homepage:
    foo: "Hello World"
    bar: "Hello Friend"
    baz: %homepage.foo%
```

 And maybe referencing also other dictionary, distinguished by dot at the beginning:

``` yml
homepage:
    foo: "Hello World"
    bar: "Hello Friend"
    baz: %.differentDictionary.abc.foo%
```

Your idea? I may implement it afterwards.

**Comment by janedbal** [comment]
I've met similar issue when trying to accomplish following use-case:

```yaml
phone:
    default: 'Phone number %number% is not valid for state %state%.'
    prefixMismatch: %phone.default%' Country code %givenPrefix% belongs to %givenPrefixState%. Expected country code is %expectedPrefix%.'
    prefixInvalid: %phone.default%' Country code is not valid.'
    invalid: %phone.default%' Please check number of digits and typing errors.'
    invalidFormat: %phone.default%
    tooLong: %phone.default%' The number is too long.'
    tooShort: %phone.default%' The number is too short.'
```

With such concatenation, you wouldn't have to repeat the base error message and its parameters all over again.
