### ISSUE TITLE
Allow easier adding of custom locale resolver

### ISSUE THREAD

**Issue by fprochazka** [Kdyby/Translation#46]
``` yml
translation:
    resolvers:
        -  Phc\Localization\WebsiteResolver
```

via @TomasVotruba at https://help.kdyby.org/question/?questionId=160#post160
