### ISSUE TITLE
Undefined index: resolvers & default resolver only

### ISSUE THREAD

**Issue by bazo** [Kdyby/Translation#60]
we use only default resolver
config looks like this

```
translation:
    default: %lang%
    whitelist: [sk, en, de, cz]
    dirs: [%appDir%/locale]
    resolvers:
        session: FALSE
        request: FALSE
        header: FALSE
```

after composer update i get the error in title. i think you broke the resolvers system with this commit https://github.com/Kdyby/Translation/commit/3673e1427b717f19decb7b965fd8995d0ec44aa9 :D

so how do i turn the default resolver back on?
